accounts:
- cpmerp/accounts/*
- cpmerp/controllers/accounts_controller.py
- cpmerp/controllers/taxes_and_totals.py

stock:
- cpmerp/stock/*
- cpmerp/controllers/stock_controller.py
- cpmerp/controllers/item_variant.py

assets:
- cpmerp/assets/*

regional:
- cpmerp/regional/*

selling:
- cpmerp/selling/*
- cpmerp/controllers/selling_controller.py

buying:
- cpmerp/buying/*
- cpmerp/controllers/buying_controller.py

support:
- cpmerp/support/*

POS:
- pos*

ecommerce:
- cpmerp/e_commerce/*

maintenance:
- cpmerp/maintenance/*

manufacturing:
- cpmerp/manufacturing/*

crm:
- cpmerp/crm/*

HR:
- cpmerp/hr/*

payroll:
- cpmerp/payroll*

projects:
- cpmerp/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['cpmerp/**/*.py']
  all: ['!cpmerp/**/test*.py']
